mysite/TO_DO/urls.py
from django.urls import path

from . import views

app_name = "TO_DO"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/update/", views.UpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.DeleteTodoView.as_view(), name="Todo_delete"),
]

urlpatterns += [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("TO_DO/", include("TO_DO.urls")),
    path('admin/', admin.site.urls),
]

mysite/TO_DO/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField("date published")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

mysite/TO_DO/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.widgets import PasswordInput, TextInput

#Create/Register user 
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


#Authenticate a user 
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())

mysite/TO_DO/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, logout
from django.contrib.auth.models import auth, User   
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django import forms

from .models import Todo
from .forms import CreateUserForm, LoginForm

# Create your views here.

@method_decorator(login_required(login_url='TO_DO:login'), name='dispatch')
class IndexView(generic.ListView):
    template_name = "TO_DO/index.html"
    context_object_name = "to_do_list"

    def get_queryset(self) -> QuerySet[Any]:
        user = self.request.user
        queryset = Todo.objects.filter(user=user)
        return queryset.order_by("-date")


@method_decorator(login_required(login_url='TO_DO:login'), name='dispatch')
class DeleteTodoView(generic.DeleteView):
    model = Todo
    template_name = "TO_DO/confirm_delete.html"
    success_url = reverse_lazy("TO_DO:index")


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ["title", "date"]
        widgets = {
            'date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


@method_decorator(login_required(login_url='TO_DO:login'), name='dispatch')
class CreateView(generic.CreateView):
    model = Todo
    form_class = TodoForm
    template_name = "TO_DO/create.html"
    success_url = reverse_lazy("TO_DO:index")

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.user = self.request.user
        return super().form_valid(form)


@method_decorator(login_required(login_url='TO_DO:login'), name='dispatch')
class UpdateView(generic.UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = "TO_DO/update.html"
    success_url = reverse_lazy("TO_DO:index")


#Authentication and login
    
def registerUser(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("TO_DO:login")
    
    context = {'registerform': form}

    return render(request, 'TO_DO/Auth/register.html', context=context)
        

def loginUser(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)

        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth.login(request, user)

                return redirect('TO_DO:index')
    
    context = {'loginform': form}
    return render(request, 'TO_DO/Auth/login.html', context=context)


def user_logout(request):
    logout(request)

    return redirect('TO_DO:login')

mysite/TO_DO/templates/TO_DO/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'TO_DO/style.css' %}">
    <title>Delete TO-DO</title>
</head>
<body>
    <header>
        <h1><a href="{% url 'TO_DO:index' %}">TO-DO</a></h1>
    </header>
    <h1 style="text-align: center; color: red;">Confirm delete of {{ todo }}</h1>
    <form method="post" action="{% url 'TO_DO:Todo_delete' todo.id %}">
        {% csrf_token %}
        <input class="delete-button" type="submit" value="Confirm delete">
    </form>
</body>
</html>

mysite/TO_DO/templates/TO_DO/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'TO_DO/style.css' %}">
    <title>Document</title>
</head>
<body>
    <header>
        <div>
            <h1><a href="{%url 'TO_DO:index' %}">TO-DO</a></h1>
            <nav>
                <ul>
                    <li><a href="{% url 'TO_DO:create' %}">Create</a></li>
                    <li><a href="{% url 'TO_DO:register' %}">Register</a></li>
                    <li><a href="{% url 'TO_DO:login' %}">Login</a></li>
                    <li><a href="{% url 'TO_DO:logout' %}">Logout</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <form class="create-form" method="post" action="{% url 'TO_DO:create' %}"> {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input class="create-button" type="submit" value="CREATE">
        </div>
    </form>
</body>
</html>

mysite/TO_DO/templates/TO_DO/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'TO_DO/style.css' %}">
</head>
<body>
    <header>
        <div>
            <h1><a href="{%url 'TO_DO:index' %}">TO-DO</a></h1>
            <nav>
                <ul>
                    <li><a href="{% url 'TO_DO:create' %}">Create</a></li>
                    <li><a href="{% url 'TO_DO:register' %}">Register</a></li>
                    <li><a href="{% url 'TO_DO:login' %}">Login</a></li>
                    <li><a href="{% url 'TO_DO:logout' %}">Logout</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <main class="index-content">
        {% if to_do_list  %}
            <ul class="todo-list">
                {% for to_do in to_do_list %}
                    <li>
                        <div>{{ to_do.title }}</div>
                        <div><a class="update" href="{% url 'TO_DO:update' to_do.id %}">UPDATE</a></div>
                        <div><a class="delete" href="{% url 'TO_DO:Todo_delete' to_do.id %}">DELETE</a></div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Nothing to do.</p>
        {% endif %}
    </main>
</body>
</html>

mysite/TO_DO/templates/TO_DO/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'TO_DO/style.css' %}">
    <title>UPDATE</title>
</head>
<body>
    <header>
        <div>
            <h1><a href="{%url 'TO_DO:index' %}">TO-DO</a></h1>
            <nav>
                <ul>
                    <li><a href="{% url 'TO_DO:create' %}">Create</a></li>
                    <li><a href="{% url 'TO_DO:register' %}">Register</a></li>
                    <li><a href="{% url 'TO_DO:login' %}">Login</a></li>
                    <li><a href="{% url 'TO_DO:logout' %}">Logout</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <form class="update-form" method="post"> {% csrf_token %}
        <div>
            {{ form.as_p }}
            <input class="submit-button" type="submit" value="UPDATE">
        </div>
    </form>
</body>
</html>